// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVYKxYcfUKNg20V5RwOTgBINkPnxOPzuI',
    appId: '1:58793517014:web:942752fe021bf03f768e77',
    messagingSenderId: '58793517014',
    projectId: 'quizora-c93f1',
    authDomain: 'quizora-c93f1.firebaseapp.com',
    storageBucket: 'quizora-c93f1.firebasestorage.app',
    measurementId: 'G-JHSGFFKRS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN7K6INxUmGx39295TpapB00XSbT4g3GM',
    appId: '1:58793517014:android:b4d899f04d1648eb768e77',
    messagingSenderId: '58793517014',
    projectId: 'quizora-c93f1',
    storageBucket: 'quizora-c93f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQaf3y7Ya_TZ7zsbUw3GO7xF0-wPuH5zo',
    appId: '1:58793517014:ios:303e941f2d3a9031768e77',
    messagingSenderId: '58793517014',
    projectId: 'quizora-c93f1',
    storageBucket: 'quizora-c93f1.firebasestorage.app',
    iosBundleId: 'com.example.quizora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQaf3y7Ya_TZ7zsbUw3GO7xF0-wPuH5zo',
    appId: '1:58793517014:ios:303e941f2d3a9031768e77',
    messagingSenderId: '58793517014',
    projectId: 'quizora-c93f1',
    storageBucket: 'quizora-c93f1.firebasestorage.app',
    iosBundleId: 'com.example.quizora',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVYKxYcfUKNg20V5RwOTgBINkPnxOPzuI',
    appId: '1:58793517014:web:d17562009211c6cf768e77',
    messagingSenderId: '58793517014',
    projectId: 'quizora-c93f1',
    authDomain: 'quizora-c93f1.firebaseapp.com',
    storageBucket: 'quizora-c93f1.firebasestorage.app',
    measurementId: 'G-SMPE3LNW6J',
  );
}
